### ISSUE TITLE
MonkeyHash

### ISSUE THREAD

**Issue by ryantummy** [puppetlabs/puppet-resource_api#198] opened 2019-08-21 22:10 UTC
## Describe the Bug
I am using the amazon_aws puppet forge module (https://forge.puppet.com/puppetlabs/amazon_aws) for provisioning instances at aws. Specifically this file https://github.com/puppetlabs/puppetlabs-amazon_aws/blob/master/lib/puppet/type/aws_instances.rb. The most recent update to puppet-agent 6.7 which included the MonkeyHash change in puppet-resource_api/lib/puppet/resource_api.rb throws this error.

14:14:39Notice: Applied catalog in 2.05 seconds
14:14:39Error: aws_instances[{:name=>"test.com", :key_name=>"test"}]: Creating: Failed after 1.76 seconds: expected params[:tags][0][:value] to be a String, got value {:name=>"test", :key_name=>"test"} (class: Puppet::ResourceApi::MonkeyHash) instead.
14:14:39Error: /Stage[main]/Main/Aws_instances[test]: Could not evaluate: Execution encountered an error
14:14:51Waiting for the instance to become available.

I am not sure whether there is a problem with this code or the amazon_aws code so please disregard if there is nothing wrong with this code.

## Expected Behavior
The instance provisions fine but something is erroring and not sure what it is.

## Steps to Reproduce
Use the amazone_aws puppet forge module to provision an instance using puppet agent 6.7. But downgrading to 6.5 where MonkeyHash isn't used works fine

## Environment
CentOS 7.6
puppet-agent 6.7

**Comment by DavidS** [comment] 2019-08-28 16:09
Hi @ryantummy , thanks for reporting this issue. I believe this is a duplicate of https://github.com/puppetlabs/puppetlabs-amazon_aws/issues/3 and it will be fixed in the next release of the module.

**Comment by DavidS** [comment] 2019-09-24 08:55
Closing as this is nothing resource_api can help with.

**Closed by DavidS** 2019-09-24 08:55 UTC
Labels: duplicate
