### ISSUE TITLE
custom_insync change message not honored in noop mode

### ISSUE THREAD

**Issue by seanmil** [puppetlabs/puppet-resource_api#307] opened 2023-01-05 15:24 UTC
While working on a new provider using the `custom_insync` feature, I noticed that while my custom change message returned from `insync?` is honored when performing a regular resource apply but not if puppet is being run with `--noop`.

In a noop run the change message returns to a generic message:
`Notice: /Stage[main]/Myprovider[foo]/rsapi_custom_insync_trigger: current_value , should be 'do_not_specify_in_manifest' (noop) (corrective)`

The expected behavior would be that the custom change message appear in both normal and noop modes.

**Comment by jordanbreen28** [comment] 2023-12-18 13:25
hey @seanmil! Thanks for raising this.
I've added this to our backlog.

**Comment by jordanbreen28** [comment] 2024-05-08 12:50
@seanmil apologies for the length of time it has taken to look into this..

can you confirm if this is still an issue? Testing on my end is showing the custom insync message on both a regular apply and `--noop` runs. If so, if you are able to reproduce and send me over a snippet of your `insync?` method and the corresponding sanitised manifest or resource thats causing the problem. Thanks

**Comment by jordanbreen28** [comment] 2024-05-08 14:27
Hi @seanmil, I've been able to track down the offending code on this issue.
The issue actually stems from the puppet source code, and not the puppet-resource_api. Essentially, there are two different methods which form the event message, one for `noop` applies and another for `no noop` applies, (see [here](https://github.com/puppetlabs/puppet/blob/ca922ca1f7c1cbd8c28b35a59c126b39b2c90778/lib/puppet/transaction/resource_harness.rb#L237C1-L254C6)) and the noop method does not call the `change_to_s` method which retrieves the custom_insync message.

I've opened https://github.com/puppetlabs/puppet/pull/9339 to see if we can get this in and fixed. I'll go ahead and close this issue since its not connected to this repo! Thanks again

**Closed by jordanbreen28** 2024-05-08 14:27 UTC
Labels: bug
